name: spielbelaberung
favicon: null
layout_spectrum: 1
typography_spectrum: 0.65161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#5ea9d7'
    - '#464646'
    - '#1d1b1c'
    - '#c1c1c1'
  brandStrength: 0.1875
  lightness: 0.75
  saturation: 0
  rhythmicContrast: 0
purpose: []
