name: spielbelaberung
favicon: null
layout_spectrum: 0.4026706318836659
typography_spectrum: 0.65161
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.875
  lightness: 0.75
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
