name: spielbelaberung
favicon: null
layout_spectrum: 0.4026706318836659
typography_spectrum: 0.2742291565518826
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.21981866820715368
  lightness: 0.3960607941262424
  saturation: 0.9705065437592566
  rhythmicContrast: 0.30978439236059785
purpose: []
